### PR TITLE
Raise exception when caps are not send before the first buffer

### LINKED ISSUE #341: Disallow sending buffers without sending caps first
Sending a buffer without caps is now possible even though many elements won't work without them (e.g. H264 encoder and decoder). Since there's no scenario, where not sending them is required, we should raise with a clear error when a buffer is sent and there are no caps set on the output pad

### PR DESCRIPTION
**Pull request by varsill**
Add ActionError exception raising when the `:buffer` action is made on pad, which does not have caps set. Add unit test and integration test checking that functionality. Change the existing tests in a`ction_handler_test.exs` and `auto_demands_test.exs` so that they are now working with pads that have the caps set before sending the first buffer.
closes #341

### CODE REVIEW

File: lib/membrane/core/element/action_handler.ex [hunk 1]
```diff
@@ -269,12 +269,16 @@ defmodule Membrane.Core.Element.ActionHandler do
           eos: %{end_of_stream?: false} <- pad_data do
       %{pid: pid, other_ref: other_ref} = pad_data
 
-      state =
-        DemandHandler.handle_outgoing_buffers(pad_ref, pad_data, buffers, state)
-        |> PadModel.set_data!(pad_ref, :start_of_stream?, true)
-
-      Message.send(pid, :buffer, buffers, for_pad: other_ref)
-      {:ok, state}
+      if state.pads.data[pad_ref].caps == nil do
```
Comment (mat-hek) [inline lib/membrane/core/element/action_handler.ex:272]: - this can be an additional clause in the `withl` above
- you can use the `pad_data` variable

File: lib/membrane/exceptions.ex [hunk 2]
```diff
@@ -117,6 +117,10 @@ defmodule Membrane.ActionError do
     "Invalid event: #{inspect(event, pretty: true)}"
   end
 
+  defp format_reason(:caps_not_sent_before_first_buffer) do
+    "Caps were not sent on this pad before the first buffer was"
```
Comment (mat-hek) [inline lib/membrane/exceptions.ex:121]:
```suggestion
    "Tried to send a buffer, while caps have not been sent on this pad"
```

File: test/membrane/core/element/action_handler_test.exs [hunk 3]
```diff
@@ -155,7 +155,7 @@ defmodule Membrane.Core.Element.ActionHandlerTest do
     end
 
     test "when element is moving to playing", %{state: state} do
-      state = state |> set_playback_state(:prepared)
+      state = state |> set_playback_state(:prepared) |> PadModel.set_data!(:output, :caps, :any)
```
Comment (mat-hek) [inline test/membrane/core/element/action_handler_test.exs:158]:
```suggestion
      state = state |> set_playback_state(:prepared) |> PadModel.set_data!(:output, :caps, :some_caps)
```

**Review by mat-hek — CHANGES_REQUESTED** [review]

File: lib/membrane/exceptions.ex (hunk 2 above)
Comment (varsill) [reply lib/membrane/exceptions.ex:121]: done

File: test/membrane/core/element/action_handler_test.exs (hunk 3 above)
Comment (varsill) [reply test/membrane/core/element/action_handler_test.exs:158]: I have found that in this test file there is `@mock_caps` defined and I have used it there.

Comment (varsill) [reply test/membrane/core/element/action_handler_test.exs:158]: done

File: lib/membrane/core/element/action_handler.ex (hunk 1 above)
Comment (varsill) [reply lib/membrane/core/element/action_handler.ex]: done

**Review by mat-hek — APPROVED** [review]
